# Generated by Django 4.0.3 on 2022-11-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_belongto_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='belongTo',
            new_name='scholarAuth',
        ),
    ]
