# Generated by Django 3.2 on 2022-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_belongto_customuser_scholarauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '学者')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scholarAuth',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userscholar',
            name='scholar',
            field=models.CharField(max_length=40),
        ),
    ]
