# Generated by Django 3.2 on 2022-12-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221209_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scholar',
            field=models.CharField(max_length=40),
        ),
    ]
