# Generated by Django 3.2 on 2022-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_sentby'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='remark',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
