# Generated by Django 3.2 on 2022-12-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notification_scholarid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_under_review', to='api.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='article',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
