# Generated by Django 3.2 on 2022-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification_paperid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='belongTo',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.IntegerField(choices=[(0, '无'), (1, '关注'), (2, '申诉接受'), (3, '申诉驳回'), (4, '门户认领成功'), (5, '门户解除'), (6, '评论论文'), (7, '回复评论')], default=0),
        ),
    ]
