# Generated by Django 3.2 on 2022-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20221211_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='commentId',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='paperName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='scholarName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='userId',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='userName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
