# Generated by Django 3.2 on 2022-12-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20221211_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='remark',
        ),
    ]
