# Generated by Django 3.2 on 2022-12-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20221211_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='category',
            new_name='type',
        ),
    ]
