# Generated by Django 3.2 on 2022-12-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_category_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='commentId',
            new_name='reviewId',
        ),
    ]
