# Generated by Django 3.2 on 2022-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_commentid_notification_reviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscholar',
            name='scholarName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
