# Generated by Django 3.2 on 2022-12-12 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userscholar_scholarname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banComment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banDuration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, '无'), (1, '关注'), (2, '申诉学者接受-给用户'), (3, '申诉学者接受-给学者'), (4, '申诉学者驳回'), (5, '门户认领成功'), (6, '门户认领失败'), (7, '申诉学术成果接受-给用户'), (8, '申诉学术成果接受-给学者'), (9, '申诉学术成果失败'), (10, '评论'), (11, '回复评论')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.IntegerField(choices=[(0, '主问题'), (1, '提问/回复')], default=0),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.IntegerField(choices=[(1, '垃圾内容'), (2, '色情内容'), (3, '非法活动'), (4, '侵犯版权'), (5, '骚扰、欺凌和威胁'), (6, '仇恨言论'), (7, '暴力内容')], default=0)),
                ('result', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reportReview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review')),
            ],
        ),
    ]
