# Generated by Django 3.2 on 2022-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221212_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='category',
            field=models.CharField(choices=[('1', '垃圾内容'), ('2', '色情内容'), ('3', '非法活动'), ('4', '侵犯版权'), ('5', '骚扰、欺凌和威胁'), ('6', '仇恨言论'), ('7', '暴力内容')], default='0', max_length=1),
        ),
    ]
